User.create!([
  {email: "akim@yahoo.com", encrypted_password: "$2a$10$nfir4uEUtbJQtxMz0hJ6huRILp0ImcIPONqrQFrJ3uAGqwjUB6G0m", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-06-07 02:04:23", last_sign_in_at: "2014-06-07 02:04:23", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: nil},
  {email: "drew@gmail.com", encrypted_password: "$2a$10$mF4lh7pppsHK7T7MOAvHCuyPR5tz/UCfKZY0t25x0A78./y.i0iDu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2014-06-13 00:21:24", last_sign_in_at: "2014-06-12 02:22:58", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: nil},
  {email: "ak@yahoo.com", encrypted_password: "$2a$10$wr72UODL7oTTYz4l2ZXdb.FK0FDbxjeUKdPd2jQLtIw1mUi9Y3Iry", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-06-12 06:33:20", last_sign_in_at: "2014-06-12 06:33:20", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", username: nil}
])
Ad.create!([
  {ad_url: "//www.youtube.com/embed/gh5xu35bAxA", cpv: 0.75, company: "Berlitz"},
  {ad_url: "//www.youtube.com/embed/AGWp57xtc10", cpv: 0.8, company: "Dropbox"},
  {ad_url: "//www.youtube.com/embed/ThzdsnXeE28", cpv: 0.2, company: "Expedia"},
  {ad_url: "//www.youtube.com/embed/6pjliE37ENY", cpv: 0.7, company: "ESPN"},
  {ad_url: "//www.youtube.com/embed/yuHHdaUux4o", cpv: 0.81, company: "Street League"},
  {ad_url: "//www.youtube.com/embed/y5gUn-aOyh4", cpv: 0.4, company: "Nike"},
  {ad_url: "//www.youtube.com/embed/wWuV85I7rJU", cpv: 0.4, company: "Movies"},
  {ad_url: "//www.youtube.com/embed/PcZapHQMz0s", cpv: 0.24, company: "Movies"},
  {ad_url: "//www.youtube.com/embed/OvgyXKDXdZY", cpv: 0.5, company: "Movies"},
  {ad_url: "//player.vimeo.com/video/22222677", cpv: 0.85, company: "Kiip"},
  {ad_url: "//www.youtube.com/embed/7Jpb2_YdxYM", cpv: 0.95, company: "Dove"}
])
AdView.create!([
  {ad_id: 9, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 3, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 1, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 4, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 9, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 2, user_id: 2},
  {ad_id: 4, user_id: 3},
  {ad_id: 2, user_id: 3},
  {ad_id: 3, user_id: 3},
  {ad_id: 3, user_id: 3},
  {ad_id: 11, user_id: 3},
  {ad_id: 9, user_id: 3},
  {ad_id: 5, user_id: 3},
  {ad_id: 1, user_id: 3},
  {ad_id: 1, user_id: 3}
])
Category.create!([
  {ad_id: 0, category: "Funny"},
  {ad_id: nil, category: "Tech"},
  {ad_id: nil, category: "Sports"},
  {ad_id: nil, category: "Travel"},
  {ad_id: nil, category: "Movie Trailers"},
  {ad_id: nil, category: "Emotional"}
])
Tagging.create!([
  {category_id: 2, ad_id: 1},
  {category_id: 3, ad_id: 2},
  {category_id: 4, ad_id: 4},
  {category_id: 9, ad_id: 3},
  {category_id: 5, ad_id: 3},
  {category_id: 4, ad_id: 5},
  {category_id: 4, ad_id: 6},
  {category_id: 8, ad_id: 7},
  {category_id: 8, ad_id: 8},
  {category_id: 8, ad_id: 9},
  {category_id: nil, ad_id: nil},
  {category_id: 9, ad_id: 11}
])
